# Generated by Django 6.0.3 on 2026-04-13 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0009_appointment_user'),
        ('learningapp', '0002_userdetails_delete_userdeatails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField()),
                ('Qualification', models.CharField(max_length=100)),
                ('year_of_exp', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.CharField(choices=[('CBC', 'cbc'), ('LFT', 'lft'), ('Urine Total Test', 'urine total test'), ('Urine Microscopic', 'urine microscopic'), ('Serum Routine', 'serum routine'), ('Thyroid', 'thyroid')], max_length=100)),
                ('lab_result', models.CharField(choices=[('PENDING', 'pending'), ('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_range', models.CharField(choices=[('NIL', 'nil'), ('POSITIVE', 'positive'), ('NEGATIVE', 'negative'), ('NORMAL', 'normal'), ('ABNORMAL', 'abnormal')], default='nil', max_length=100)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('test_cost', models.IntegerField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.userdetails')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
