# Generated by Django 6.0.3 on 2026-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labReports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_tests',
            name='lab_test',
            field=models.CharField(choices=[('CBC', 'cbc'), ('LFT', 'lft'), ('KFT', 'kft'), ('RFT', 'rft'), ('Urine Total Test', 'urine total test'), ('Urine Microscopic', 'urine microscopic'), ('Serum Routine', 'serum routine'), ('Thyroid Profile (T3, T4, TSH)', 'thyroid'), ('Fasting Blood Sugar (FBS)', 'fbs'), ('Postprandial Blood Sugar (PPBS)', 'ppbs'), ('HbA1c', 'hba1c'), ('Lipid Profile', 'lipid profile'), ('Bilirubin Total/Direct', 'bilirubin'), ('Serum Creatinine', 'serum creatinine'), ('Blood Urea', 'blood urea'), ('Sodium', 'sodium'), ('Potassium', 'potassium'), ('Chloride', 'chloride'), ('Troponin I', 'troponin'), ('CK-MB', 'ckmb'), ('Dengue Test', 'dengue'), ('Malaria Test', 'malaria'), ('COVID-19 RT-PCR', 'covid'), ('Widal Test', 'widal'), ('HIV Test', 'hiv'), ('HBsAg (Hepatitis B)', 'hbsag'), ('HCV (Hepatitis C)', 'hcv'), ('Vitamin D', 'vitamin d'), ('Vitamin B12', 'vitamin b12'), ('Prolactin', 'prolactin'), ('Testosterone', 'testosterone'), ('Estrogen', 'estrogen'), ('Prothrombin Time (PT)', 'pt'), ('INR', 'inr'), ('X-Ray', 'xray'), ('Ultrasound (USG)', 'ultrasound'), ('CT Scan', 'ct scan'), ('MRI Scan', 'mri')], max_length=100),
        ),
    ]
