# Generated by Django 6.0.3 on 2026-04-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0009_appointment_user'),
        ('learningapp', '0002_userdetails_delete_userdeatails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('doa', models.DateField(verbose_name='Date of Admission')),
                ('dod', models.DateField(verbose_name='Date of Discharge')),
                ('room_type', models.CharField(choices=[('common_ward', 'Common Ward'), ('semi_pvt', 'Semi-Private'), ('private_ac', 'Private AC'), ('private_nonac', 'Private Non-AC'), ('delux', 'Delux')], max_length=20)),
                ('food_required', models.BooleanField(default=False)),
                ('total_days', models.PositiveIntegerField()),
                ('bed_charges', models.IntegerField(default=0)),
                ('nursing_charges', models.IntegerField(default=0)),
                ('doctor_visit_charges', models.IntegerField(default=0)),
                ('misc_charges', models.IntegerField(default=0)),
                ('food_charges', models.IntegerField(default=0)),
                ('medicine_charges', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.userdetails')),
            ],
        ),
    ]
