# Generated by Django 6.0.3 on 2026-04-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargesummary',
            old_name='food_required',
            new_name='food_coffee_tea',
        ),
        migrations.RenameField(
            model_name='dischargesummary',
            old_name='bed_charges',
            new_name='lab_charges',
        ),
        migrations.RenameField(
            model_name='dischargesummary',
            old_name='doctor_visit_charges',
            new_name='room_charges',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='misc_charges',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='nursing_charges',
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='food_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='food_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='food_morning',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('online', 'Online Banking')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('discharge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.dischargesummary')),
            ],
        ),
    ]
