# Generated by Django 6.0.3 on 2026-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLDOCTORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialized', models.CharField(choices=[('GENERAL MEDICINE', 'general medicine'), ('CARDIOLOGIST', 'cardiologist'), ('ENT', 'ent'), ('ORTHOPENDIC', 'orthopendic'), ('EYE SPECIALIST', 'eye specialist'), ('DENTIST', 'dentist'), ('OTHERS', 'others')])),
                ('yoe', models.IntegerField()),
                ('Lic_no', models.CharField(max_length=100)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
