# Generated by Django 6.0.3 on 2026-04-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='donts',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='dos',
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(choices=[('DENTAL CARE', 'Dental Care'), ('HEART CHECKUP', 'Heart Checkup'), ('SKIN TREATMENT', 'Skin Treatment'), ('EYE CHECKUP', 'Eye Checkup'), ('ORTHOPEDIC CARE', 'Orthopedic Care'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('GENERAL CHECKUP', 'General Checkup'), ('ENT TREATMENT', 'ENT Treatment'), ('DIABETES CARE', 'Diabetes Care')]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
