# Generated by Django 6.0.3 on 2026-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_treatment_created_at_remove_treatment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(max_length=100),
        ),
    ]
