# Generated by Django 6.0.3 on 2026-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_treatment_treatment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('consultation_charges', models.CharField(default=550, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(),
        ),
    ]
