# Generated by Django 6.0.3 on 2026-04-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_appointment_alter_treatment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(choices=[('GENERAL MEDICINE', 'general medicine'), ('CARDIOLOGIST', 'cardiologist'), ('ENT', 'ent'), ('ORTHOPENDIC', 'orthopendic'), ('EYE SPECIALIST', 'eye specialist'), ('DENTIST', 'dentist'), ('OTHERS', 'others')]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(choices=[('DENTAL CARE', 'Dental Care'), ('HEART CHECKUP', 'Heart Checkup'), ('SKIN TREATMENT', 'Skin Treatment'), ('EYE CHECKUP', 'Eye Checkup'), ('ORTHOPEDIC CARE', 'Orthopedic Care'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('GENERAL CHECKUP', 'General Checkup'), ('ENT TREATMENT', 'ENT Treatment'), ('DIABETES CARE', 'Diabetes Care')]),
        ),
    ]
